2023-10-02 10:44:06 [scrapy.utils.log] INFO: Scrapy 2.11.0 started (bot: price_alert)
2023-10-02 10:44:06 [scrapy.utils.log] INFO: Versions: lxml 4.9.3.0, libxml2 2.10.3, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 22.10.0, Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0], pyOpenSSL 23.2.0 (OpenSSL 3.1.3 19 Sep 2023), cryptography 41.0.4, Platform Linux-6.2.0-33-generic-x86_64-with-glibc2.35
2023-10-02 10:44:06 [scrapy.addons] INFO: Enabled addons:
[]
2023-10-02 10:44:06 [asyncio] DEBUG: Using selector: EpollSelector
2023-10-02 10:44:06 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2023-10-02 10:44:06 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.unix_events._UnixSelectorEventLoop
2023-10-02 10:44:06 [scrapy.extensions.telnet] INFO: Telnet Password: fd8cfc79fd60be52
2023-10-02 10:44:06 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapeops_scrapy.extension.ScrapeOpsMonitor']
2023-10-02 10:44:06 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'price_alert',
 'FEED_EXPORT_ENCODING': 'utf-8',
 'LOG_FILE': 'logs/price_alert/amazon/be9d2180612911ee90b9c3b520c834d6.log',
 'NEWSPIDER_MODULE': 'price_alert.spiders',
 'REQUEST_FINGERPRINTER_IMPLEMENTATION': '2.7',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['price_alert.spiders'],
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2023-10-02 10:44:06 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapeops_scrapy.middleware.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-10-02 10:44:06 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-10-02 10:46:16 [root] INFO: Error: Error in error logger
2023-10-02 10:46:16 [root] INFO: 'LogRecord' object has no attribute 'message'
Traceback (most recent call last):
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapeops_scrapy/core/error_logger.py", line 138, in emit
    errorMessage = record.message
AttributeError: 'LogRecord' object has no attribute 'message'
2023-10-02 10:46:16 [twisted] CRITICAL: Unhandled error in Deferred:
2023-10-02 10:46:16 [root] INFO: Error: Error in error logger
2023-10-02 10:46:16 [root] INFO: 'LogRecord' object has no attribute 'message'
Traceback (most recent call last):
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapeops_scrapy/core/error_logger.py", line 138, in emit
    errorMessage = record.message
AttributeError: 'LogRecord' object has no attribute 'message'
2023-10-02 10:46:16 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/sousa/.local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapy/crawler.py", line 158, in crawl
    self.engine = self._create_engine()
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapy/crawler.py", line 172, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapy/core/engine.py", line 100, in __init__
    self.scraper = Scraper(crawler)
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapy/core/scraper.py", line 109, in __init__
    self.itemproc: ItemPipelineManager = itemproc_cls.from_crawler(crawler)
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapy/middleware.py", line 90, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapy/middleware.py", line 67, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/home/sousa/.local/lib/python3.10/site-packages/scrapy/utils/misc.py", line 194, in create_instance
    instance = objcls(*args, **kwargs)
  File "/home/sousa/price_alert/price_alert/price_alert/pipelines.py", line 17, in __init__
    self.connection = psycopg2.connect(host=hostname, port=port, user=username, password=password, dbname=database)
  File "/home/sousa/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "containers-us-west-183.railway.app" (35.233.170.156), port 6265 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

